stages:
  - deploy

deploy:
  stage: deploy
  image: alpine
  script:
    - apk add --no-cache openssh-client
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no -p 22 "$SSH_USER"@"$SSH_HOST" ls -la
 
