image: docker:latest

stages:
  - build

build-code-job:
  stage: build
  script:
    - docker run cmd.cat/sshpass sshpass
    - sshpass -p "$SSH_PASSWORD" ssh -p 22 "$SSH_USER"@"$SSH_HOST"
    - echo "test 11team hj"
    - ls
