image: node:latest

cache:
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

before_script:
  - apt-get update && apt-get upgrade -y && \
    apt-get install -y nodejs \
    npm 

building:
  stage: build
  variables:
    NODE_ENV: "development"
  script:
    - npm i
  type: build
  tags:
    - ci
  only:
    - tags
    - master
