stages:
  - deploy

deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install -y sshpass
    - sshpass -p "$SSH_PASSWORD" ssh "$SSH_USER"@"$SSH_HOST"
    - ls -la
 
