image: node:latest

cache:
    paths:
        - node_modules/

stages:
    - build
    - lint
    - test
    - deploy

before_script:
    - npm install

build:
    stage: build
    tags:
      - ci
    script:
        - npm run build
    artifacts:
      paths:
        - /home/gitlab-runner/

