cache:
    paths:
        - node_modules/

stages:
    - build
    - lint
    - test
    - deploy

before_script:
    - sudo apt-get install -y npm
    - npm install

build:
    image: node:12.13.0-alpine
    stage: build
    tags:
      - ci
    script:
        - npm run build
    artifacts:
      paths:
        - /home/gitlab-runner/

