image: node:latest

cache:
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

before_script:
  - npm set progress=false

building:
  stage: build
  variables:
    NODE_ENV: "development"
  script:
    - npm i --no-optional
    - npm run build
  type: build
  tags:
    - ci
  only:
    - tags
    - master
