cache:
    paths:
        - node_modules/

stages:
    - build
    - lint
    - test
    - deploy


build:
    image: node:12.13.0-alpine
    stage: build
    tags:
      - ci
    before_script:
        - npm install
    script:
        - npm run build
    artifacts:
      paths:
        - /home/gitlab-runner/

